export const patientsData = [
  {
    id: "1",
    avatar: "OR",
    name: "Olivia Rhye",
    dateOfBirth: "9 May 2000",
    gender: "Male",
    contact: "054077343",
    associatedPharmacy: "Humble Pharmacy",
    lastVisit: "7 May, 2025",
    actions: "",
  },
  {
    id: "2",
    avatar: "PB",
    name: "Phoenix Baker",
    dateOfBirth: "9 May 2000",
    gender: "Female",
    contact: "054077343",
    associatedPharmacy: "Humble Pharmacy",
    lastVisit: "7 May, 2025",
    actions: "",
  },
  {
    id: "3",
    avatar: "LS",
    name: "Lana Steiner",
    dateOfBirth: "9 May 2000",
    gender: "Male",
    contact: "054077343",
    associatedPharmacy: "Humble Pharmacy",
    lastVisit: "7 May, 2025",
    actions: "",
  },
  {
    id: "4",
    avatar: "DW",
    name: "Demi Wilkinson",
    dateOfBirth: "9 May 2000",
    gender: "Male",
    contact: "054077343",
    associatedPharmacy: "Humble Pharmacy",
    lastVisit: "7 May, 2025",
    actions: "",
  },
  {
    id: "5",
    avatar: "CW",
    name: "Candice Wu",
    dateOfBirth: "9 May 2000",
    gender: "Male",
    contact: "054077343",
    associatedPharmacy: "Humble Pharmacy",
    lastVisit: "7 May, 2025",
    actions: "",
  },
  {
    id: "6",
    avatar: "NC",
    name: "Natali Craig",
    dateOfBirth: "9 May 2000",
    gender: "Male",
    contact: "054077343",
    associatedPharmacy: "Humble Pharmacy",
    lastVisit: "7 May, 2025",
    actions: "",
  },
  {
    id: "7",
    avatar: "DC",
    name: "Drew Cano",
    dateOfBirth: "9 May 2000",
    gender: "Male",
    contact: "054077343",
    associatedPharmacy: "Humble Pharmacy",
    lastVisit: "7 May, 2025",
    actions: "",
  },
  {
    id: "8",
    avatar: "OD",
    name: "Orlando Diggs",
    dateOfBirth: "9 May 2000",
    gender: "Male",
    contact: "054077343",
    associatedPharmacy: "Humble Pharmacy",
    lastVisit: "7 May, 2025",
    actions: "",
  },
  {
    id: "9",
    avatar: "AL",
    name: "Andi Lane",
    dateOfBirth: "9 May 2000",
    gender: "Male",
    contact: "054077343",
    associatedPharmacy: "Humble Pharmacy",
    lastVisit: "7 May, 2025",
    actions: "",
  },
  {
    id: "10",
    avatar: "KM",
    name: "Kate Morrison",
    dateOfBirth: "9 May 2000",
    gender: "Male",
    contact: "054077343",
    associatedPharmacy: "Humble Pharmacy",
    lastVisit: "7 May, 2025",
    actions: "",
  },
];

export const pharmaciesData = [
  {
    id: "1",
    pharmacyName: "Humble Pharmacy",
    email: "eric@gmail.com",
    type: "Acrrd",
    contact: "2",
    location: "GD",
    page: "Orlando Page",
    status: "rejected",
    actions: "",
  },
  {
    id: "2",
    pharmacyName: "Humble Pharmacy",
    email: "eric@gmail.com",
    type: "Acrrd",
    contact: "9",
    location: "GD",
    page: "Orlando Page",
    status: "rejected",
    actions: "",
  },
  {
    id: "3",
    pharmacyName: "Humble Pharmacy",
    email: "eric@gmail.com",
    type: "Yeezy",
    contact: "2",
    location: "GD",
    page: "Orlando Page",
    status: "active",
    actions: "",
  },
  {
    id: "4",
    pharmacyName: "Humble Pharmacy",
    email: "eric@gmail.com",
    type: "Yeezy",
    contact: "2",
    location: "GD",
    page: "Orlando Page",
    status: "rejected",
    actions: "",
  },
  {
    id: "5",
    pharmacyName: "Humble Pharmacy",
    email: "eric@gmail.com",
    type: "Ni",
    contact: "1",
    location: "GD",
    page: "Orlando Page",
    status: "active",
    actions: "",
  },
  {
    id: "6",
    pharmacyName: "Humble Pharmacy",
    email: "eric@gmail.com",
    type: "Yeezy",
    contact: "2",
    location: "GD",
    page: "Orlando Page",
    status: "rejected",
    actions: "",
  },
  {
    id: "7",
    pharmacyName: "Humble Pharmacy",
    email: "eric@gmail.com",
    type: "Messaging",
    contact: "2",
    location: "GD",
    page: "Orlando Page",
    status: "active",
    actions: "",
  },
  {
    id: "8",
    pharmacyName: "Humble Pharmacy",
    email: "eric@gmail.com",
    type: "Acrrd",
    contact: "2",
    location: "GD",
    page: "Orlando Page",
    status: "active",
    actions: "",
  },
  {
    id: "9",
    pharmacyName: "Humble Pharmacy",
    email: "eric@gmail.com",
    type: "Acrrd",
    contact: "25",
    location: "GD",
    page: "Orlando Page",
    status: "active",
    actions: "",
  },
  {
    id: "10",
    pharmacyName: "Humble Pharmacy",
    email: "eric@gmail.com",
    type: "Acrrd",
    contact: "2",
    location: "GD",
    page: "Orlando Page",
    status: "active",
    actions: "",
  },
];

export const suppliersData = [
  {
    id: "1",
    supplier: "Supplier Company",
    email: "contact@supplier.com",
    product: "Layout",
    location: "GD",
    page: "Orlando Page",
    date: "054077343",
    actions: "",
  },
  {
    id: "2",
    supplier: "Supplier Company",
    email: "contact@supplier.com",
    product: "Layout",
    location: "GD",
    page: "Orlando Page",
    date: "054077343",
    actions: "",
  },
  {
    id: "3",
    supplier: "Supplier Company",
    email: "contact@supplier.com",
    product: "Email",
    location: "GD",
    page: "Orlando Page",
    date: "054077343",
    actions: "",
  },
  {
    id: "4",
    supplier: "Supplier Company",
    email: "contact@supplier.com",
    product: "Layout",
    location: "GD",
    page: "Orlando Page",
    date: "054077343",
    actions: "",
  },
  {
    id: "5",
    supplier: "Supplier Company",
    email: "contact@supplier.com",
    product: "Layout",
    location: "GD",
    page: "Orlando Page",
    date: "054077343",
    actions: "",
  },
  {
    id: "6",
    supplier: "Supplier Company",
    email: "contact@supplier.com",
    product: "Layout",
    location: "GD",
    page: "Orlando Page",
    date: "054077343",
    actions: "",
  },
  {
    id: "7",
    supplier: "Supplier Company",
    email: "contact@supplier.com",
    product: "Layout",
    location: "GD",
    page: "Orlando Page",
    date: "054077343",
    actions: "",
  },
  {
    id: "8",
    supplier: "Supplier Company",
    email: "contact@supplier.com",
    product: "Layout",
    location: "GD",
    page: "Orlando Page",
    date: "054077343",
    actions: "",
  },
  {
    id: "9",
    supplier: "Supplier Company",
    email: "contact@supplier.com",
    product: "Layout",
    location: "GD",
    page: "Orlando Page",
    date: "054077343",
    actions: "",
  },
  {
    id: "10",
    supplier: "Supplier Company",
    email: "contact@supplier.com",
    product: "Layout",
    location: "GD",
    page: "Orlando Page",
    date: "054077343",
    actions: "",
  },
];

export const patientColumns = [
  { key: "avatar", label: "", width: "w-12" },
  { key: "name", label: "Name" },
  { key: "dateOfBirth", label: "Date of Birth" },
  { key: "gender", label: "Gender" },
  { key: "contact", label: "Contact" },
  { key: "associatedPharmacy", label: "Associated Pharmacy" },
  { key: "lastVisit", label: "Last Visit" },
  { key: "actions", label: "Actions", width: "w-16" },
];

export const pharmacyColumns = [
  { key: "pharmacyName", label: "Pharmacy Name" },
  { key: "email", label: "Email" },
  { key: "type", label: "Type" },
  { key: "contact", label: "Contact" },
  { key: "location", label: "Location" },
  { key: "page", label: "Page" },
  { key: "status", label: "Status" },
  { key: "actions", label: "Actions", width: "w-16" },
];

export const supplierColumns = [
  { key: "supplier", label: "Supplier" },
  { key: "email", label: "Email" },
  { key: "product", label: "Product" },
  { key: "location", label: "Location" },
  { key: "page", label: "Page" },
  { key: "date", label: "Date" },
  { key: "actions", label: "Actions", width: "w-16" },
];
